# Generated by Django 2.2 on 2020-08-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=24, null=True, verbose_name='订单名')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='金额')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
    ]
