# Generated by Django 2.2 on 2020-09-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=24)),
                ('level', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24)),
                ('mobile', models.CharField(max_length=11, null=True)),
                ('is_super', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
                ('state', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='role',
            name='user_info',
            field=models.ManyToManyField(related_name='users', to='user.UserInfo'),
        ),
    ]
