# Generated by Django 2.2 on 2020-09-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200909_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='type',
            new_name='is_super',
        ),
    ]
