# Generated by Django 2.2 on 2020-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_info',
            field=models.ManyToManyField(blank=True, related_name='roles', to='user.UserInfo'),
        ),
    ]
