# Generated by Django 2.2 on 2020-09-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        ('user', '0007_auto_20200914_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='rights',
            field=models.ManyToManyField(blank=True, related_name='roles', to='web.Right'),
        ),
    ]
